version: 2

refrences:
  cache-options: &cache-options
    key: package-cache-{{ .Branch }}-{{ .Revision }}

jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          <<: *cache-options
      - run:
          name: npm-install
          command: npm install
      - run:
          name: test-reporter-setup
          command: npm install jest-junit --no-save
      - save_cache:
          <<: *cache-options
          paths:
            - ./node_modules

  linter:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          <<: *cache-options
      - run:
          name: linter
          command: ./node_modules/.bin/standard

  test:
    docker:
      - image: circleci/node:8
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: dbuser
          POSTGRES_DB: _
    steps:
      - checkout
      - restore_cache:
          <<: *cache-options
      - run:
          name: display-node-version
          command: node --version
      - run:
          name: display-npm-version
          command: npm --version
      - run:
          name: Setup PSQL Databases
          command: |
            sudo apt install -y postgresql-client
            createdb test_source
            createdb test_datawarehouse
      - run:
          name: test-reporter-setup
          command: mkdir ./junit
      - run:
          name: test
          command: ./node_modules/.bin/jest --ci --testResultsProcessor="jest-junit" --runInBand
          environment:
            NODE_ENV: test
            JEST_JUNIT_OUTPUT: reports/junit/jest.xml
            TEST_SOURCE: postgresql://dbuser@localhost:5432/test_source
            TEST_DESTINATION: postgresql://dbuser@localhost:5432/test_datawarehouse
          when: always
      - store_test_results:
          path: ./reports/junit/
      - store_artifacts:
          path: ./reports/junit/

workflows:
  version: 2
  test-all-node-versions:
    jobs:
      - build
      - linter:
          requires:
            - build
      - test:
          requires:
            - build
            - linter
